language: node_js

node_js:
- node

script:
- yarn build

deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: 5YfrGS9dinkirwE7QwrQBbr40kFDSnZ8JXMSms/a6/P3yeAZlmHtFKeB6RSgTvtf/jTjCkuTYDEC09AYdIBnWodmgCtxDcqWn+g91PTnjS5pf3F54aAAupiEPuSBSZ50Ct5AzvFo/Gof3v1FokIa8+JDBceBvagLJkPK1LHE8yE9TeXk5Z4J8HMYexR2Y0LoN+PYwMHS6HHSSNOEfC8DvSwhgfTjTQ3SE1tTz7Yidb+KqGF5jwvVFahvzj3eZGZB12V1UiqORg47SQZQ9TtiB7fOzQGfawTkKdUEM6zAEbIsvVQPAwJN+k4Ir22p6KOyPWHeXLu9vC/5/MkR87KU7/a6rjn3fbHX1jLcuDJbKQbNLeqwclQV0Hdlxb+6W85O8bfox/O/fPoXSHPYDsP/WJhIdWmsBGyTOEhkZTdMxdRpRQCr4RlZ+W1FwEPKVkpWfW97JdpqHl3j4mrLOzZHxDZfmaI9JhfLRdXqk3G4FGTB2GMK67rdr9pZivWuqrVAKYo4NbtzfGY6STzu3c1lN8n8qcvImeaA2lRpkdUygsQamopcBSKu6l9JeJ9ndaIw4Ivi6XyQhTLXQv73HgyOQx7KWBOOETLkuZnWtjlmgQtYvKXSJjHNu9RLjJEr7dEHa2u62PE/oTTubndK6cILnsw9QIIV3qQArvl9hxHSBrg=
  api_key:
    secure: GJg6xRCZfRJtWWir7Zgl40mKpZ9Hh48pBmAraWambdB1RynyLruQ4Ax2ILqkX1zBCOqOXgxsEX7dafIYCaOOD4Crt2z2ec0X8NMwwoozA/m/sxWyHgObF6l+gWY8zgrUqKnUb9Hzk+gYWX3tuKq0J53AVqGX9gJRugHxSJl5MzOLTf4leoXSa2PD1qjuDjvNBSs3pi4b5zD+vO9aXNJmUlE1+wM5D0qOefU4SD2t6/uqN/eCjBp2MnwSJhMg+vp99mPAr0r5e2w5euMH74l9RuqIS7wosq2+AyrI+HF0AvA7pwBFUOAurOhmoYSkIyDwKwiUzilpJ1pNGuJluvyyoip2+5PRKJJGlaDhTWnztigltJB4Dw+xWS/X6uynBVm/dZpdaE33WhdNLYhB0gmVYXTVbvVa1HWUpAprSAup8MFqxndsUtB6y4NQkMbH72vymNrM9X20NvSGRzngOCbSRsCFPN3EfCPpxBE2NCqttbBZuhx35vLX7EsoYGSFsGa0qUy7cLjpmJ4agarc9YX7Bn7UTmgqZJ3S9eRG3KkdcK111HPJOoAPCDsy4CP+Lw6APUnza4a0I+xAuriYJ0apgKVo54/pYpNfX22Q7nROl/RlYjTEK+/Dye2yCk4/9i9CZm2VVRY0dIRvfJwPWF8d5A1Y9QV/JiPDbqVWq1x1wWk=
  on:
    tags: true
